### ISSUE TITLE
Not accurate deocumentation

### ISSUE THREAD

**Issue by one-more-alex** [mceachen/with_advisory_lock#18]
As i seen by usage example, method used as instance method.
It is confusing as one may think it is like SQL row lock.
Please emphasize in docs that this it is class method. It is relying on locks string only without any relation to class at all... Really, like some kind of helper...
So should not be illusion of row locking emulation....

BTW, you may introduce per instance locking by using lock string like "[User 11]" or so. Then lock_name may be some suffix of this.

**Comment by mceachen** [comment]
Please read the lock types section of the [readme](https://github.com/mceachen/with_advisory_lock#lock-types).
